ixfield_device_control:
  name: "IXField Device Control"
  description: "Control all aspects of an IXField device"
  target:
    entity:
      integration: ixfield
  fields:
    device_id:
      description: "The device ID to control"
      example: "device_123"
      required: true
      selector:
        text:
    controls:
      description: "Control settings to apply"
      example:
        circulation_pump: true
        target_temperature: 25.5
      required: false
      selector:
        object:
          fields:
            circulation_pump:
              description: "Turn circulation pump on/off"
              example: true
              selector:
                boolean:
            lighting:
              description: "Turn lighting on/off"
              example: false
              selector:
                boolean:
            counterflow:
              description: "Turn counterflow on/off"
              example: true
              selector:
                boolean:
            target_temperature:
              description: "Target water temperature in Celsius"
              example: 25.5
              selector:
                number:
                  min: 0
                  max: 40
                  step: 0.5
                  unit_of_measurement: "°C"
            target_orp:
              description: "Target ORP value in mV"
              example: 650
              selector:
                number:
                  min: 100
                  max: 800
                  step: 10
                  unit_of_measurement: "mV"
            target_ph:
              description: "Target pH value"
              example: 7.4
              selector:
                number:
                  min: 7
                  max: 8
                  step: 0.05
            agent_volume:
              description: "Remaining Agent A volume in liters"
              example: 45.2
              selector:
                number:
                  min: 0
                  max: 60
                  step: 0.1
                  unit_of_measurement: "L"
            heater_mode:
              description: "Heater mode setting"
              example: "AUTO"
              selector:
                select:
                  options:
                    - "HEATING"
                    - "AUTO"
                    - "DISABLED"

ixfield_device_service_sequence:
  name: "IXField Device Service Sequence"
  description: "Start a service sequence on an IXField device"
  target:
    entity:
      integration: ixfield
  fields:
    device_id:
      description: "The device ID to control"
      example: "device_123"
      required: true
      selector:
        text:
    sequence_name:
      description: "Name of the service sequence to start"
      example: "dosingPumpA"
      required: true
      selector:
        select:
          options:
            - "dosingPumpA"
            - "mainPumpOnly"
            - "phProbeOnePointCalibration"
            - "phProbeTwoPointCalibration"
            - "orpProbeCheck"
            - "orpProbeOffsetCalibration"
            - "mainPumpTest"

ixfield_device_status:
  name: "IXField Device Status"
  description: "Get comprehensive status of an IXField device"
  target:
    entity:
      integration: ixfield
  fields:
    device_id:
      description: "The device ID to get status for"
      example: "device_123"
      required: true
      selector:
        text:

ixfield_device_refresh:
  name: "IXField Device Refresh"
  description: "Manually refresh data for an IXField device"
  target:
    entity:
      integration: ixfield
  fields:
    device_id:
      description: "The device ID to refresh"
      example: "device_123"
      required: true
      selector:
        text:

ixfield_reload_sensors:
  name: "IXField Reload Sensors"
  description: "Reload all sensors for all IXField integrations (refresh data without rediscovery)"
  target:
    entity:
      integration: ixfield

ixfield_reenumerate_sensors:
  name: "IXField Re-enumerate Sensors"
  description: "Re-enumerate all sensors for all IXField integrations (rediscover all entities)"
  target:
    entity:
      integration: ixfield

ixfield_reload_integration:
  name: "IXField Reload Integration"
  description: "Reload a specific IXField integration"
  target:
    entity:
      integration: ixfield
  fields:
    entry_id:
      description: "The config entry ID to reload"
      example: "abc123def456"
      required: true
      selector:
        text:

ixfield_get_device_info:
  name: "IXField Get Device Info"
  description: "Get comprehensive device information including address and contact details"
  target:
    entity:
      integration: ixfield
  fields:
    device_id:
      description: "The device ID to get information for"
      example: "device_123"
      required: true
      selector:
        text:

ixfield_configure_control_mappings:
  name: "IXField Configure Control Mappings"
  description: "Configure custom control mappings for IXField devices"
  target:
    entity:
      integration: ixfield
  fields:
    mappings:
      description: "Custom control mappings to configure"
      example:
        custom_control_name:
          sensor_patterns: ["target*"]
          description: "Custom temperature control"
          type: "temperature"
          unit: "°C"
      required: true
      selector:
        object:
          fields:
            custom_control_name:
              selector:
                object:
                  fields:
                    sensor_patterns:
                      description: "List of sensor name patterns to match"
                      example: ["target*", "exactSensorName"]
                      selector:
                        select:
                          multiple: true
                          options:
                            - "exactSensorName"
                            - "*WithSettings"
                            - "target*"
                    description:
                      description: "Description of this control"
                      example: "Custom temperature control"
                      selector:
                        text:
                    type:
                      description: "Control type (boolean, temperature, number, enum, string)"
                      example: "temperature"
                      selector:
                        select:
                          options:
                            - "boolean"
                            - "temperature"
                            - "number"
                            - "enum"
                            - "string"
                    unit:
                      description: "Unit of measurement (optional)"
                      example: "°C"
                      selector:
                        text:

ixfield_get_available_controls:
  name: "IXField Get Available Controls"
  description: "Get available controls for a specific device"
  target:
    entity:
      integration: ixfield
  fields:
    device_id:
      description: "The device ID to get available controls for"
      example: "device_123"
      required: true
      selector:
        text: